/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example

import com.example.tutorial.protos.AddressBook

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
